name: Publish Python Package
env:
  python_version: 3.8
on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Install poetry & dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
      - name: Run tests
        run: |
          python -m poetry run python -m pytest -v tests


  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python_version }}
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    -
      name: Build package
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
