name: Test Python Package
env:
  python_version: 3.9
on:
  push:
    branches:
      - master
      - main
    paths:
      - mobileiron-api/**
      - poetry.lock
      - pyproject.toml
      - .github/workflows/test.yml
  pull_request:
    paths:
      - mobileiron-api/**
      - poetry.lock
      - pyproject.toml
      - .github/workflows/test.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Install poetry & dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
          ~/.local/bin/poetry --version
          ~/.local/bin/poetry install
      - name: Run tests
        run: |
          ~/.local/bin/poetry run python -m pytest -v testing
